version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      - NODE_ENV=production
