version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - 3000:3000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - 80:80
